nginx:
  image: nginx:mainline-alpine
  restart: always 
  ports:
    - "80"
  links:
    - "phpfpm"
  volumes:
    - /path/to/app:/var/www/html/
    - /path/to/config/default.conf:/etc/nginx/conf.d/default.conf
   environment:
    - VIRTUAL_HOST={{VHOST_NAME}}
phpfpm:
  image: yourtion/php-fpm-alpine
  restart: always 
  ports:
    - "9000:9000"
  volumes:
    - /path/to/ap:/var/www/html/
  links:
    - "mysql"
mysql:
  image: mysql:5.5
  restart: always 
  ports:
    - "3306"
  volumes:
    - /path/to/mysql-data:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD : 123456
